# Generated by Django 3.1.3 on 2020-12-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('imagem', models.CharField(max_length=255)),
                ('descrição', models.TextField()),
                ('categoria', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
