# Generated by Django 3.1.3 on 2020-12-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[(0, 'Hambúrguer de Carne'), (1, 'Hambúrguer de Frango'), (2, 'Acompanhamento'), (3, 'Sobremesa'), (4, 'Vegetariano')], max_length=4),
        ),
    ]
