# Generated by Django 3.1.3 on 2020-12-04 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promocoes', '0003_auto_20201204_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocao',
            name='favoritos',
        ),
        migrations.AddField(
            model_name='promocao',
            name='favoritos',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
